### ISSUE TITLE
bats-file update to 0.4.0

### ISSUE THREAD

**Issue by jetmartin** [kaos/homebrew-shell#23]
Hi,

The current brew install for bats-file is `0.3.0`.
The module has been updated to `0.4.0`.
I assume the update must be done in `homebrew-shell/Formula/bats-file.rb`

Sorry if I didn't made a PR as I'm not sure about the sha256 to provide bellow :
```rb
  url "https://github.com/bats-core/bats-file/archive/refs/tags/v0.4.0.tar.gz"
  sha256 ""
```

Best

Jetmartin

**Comment by kaos** [comment]
> Sorry if I didn't made a PR as I'm not sure about the sha256 to provide bellow :
> 
> ```ruby
>   url "https://github.com/bats-core/bats-file/archive/refs/tags/v0.4.0.tar.gz"
>   sha256 ""
> ```
> 

Thanks!

It would be:
```
❯ curl -fsL https://github.com/bats-core/bats-file/archive/refs/tags/v0.4.0.tar.gz | shasum -a 256
9b69043241f3af1c2d251f89b4fcafa5df3f05e97b89db18d7c9bdf5731bb27a  -
```

**Comment by jetmartin** [comment]
Thank you,
I've made the PR.
